BaseUrl= "http://hilaozi.com/"
LanguageCode= "en-US"
Title= "嗨，老子"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true
theme = "hugo-theme-air"
[params]
  description = "人法地，地法天，天法道，道法自然"
  cover = "images/user.jpg"
  author = "quanke"
  authorlocation = ""
  authorwebsite = "http://quanke.name"
  bio= "天下皆知美之为美"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "quanke"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
